
# Keep this help dry. For example, we don't document the task composer-install
# because the task init is already documented.
help:
	@printf "\033[33m Usage:\033[39m\n"
	@printf "  make COMMAND\n"
	@printf "\n"
	@printf "\033[33m gazr.io tasks:\033[39m\n"
	@printf "\033[32m   init              \033[39m   Bootstrap your application.\n"
	@printf "\033[32m   style             \033[39m   Check lint, code styling rules.\n"
	@printf "\n"
	@printf "\033[33m other helpful tasks:\033[39m\n"
	@printf "\033[32m   clean             \033[39m   Clean everything generated by the application.\n"
	@printf "\n"
	@printf "\033[33m composer tasks:\033[39m\n"
	@printf "\033[32m   composer          \033[39m   Print composer command.\n"
	@printf "\n"

_FMT="    \033[38;5;106m%s\033[39m\n"
_WRN="    \033[38;5;208m%s\033[39m\n"

PHP_VERSION ?= 7.1
DOCKER_ORGS ?= juliendufresne
DOCKER_RUN_OPTS=--rm --name $@ --volume $(CURDIR):/app -u $(shell id -u):$(shell id -g)

###> gazr.io tasks ###
.PHONY: init
init: composer.lock

.PHONY: style
style: composer-validate
###< gazr.io tasks ###

###> other helpful tasks ###
.PHONY: clean
clean: composer-clean
###< other helpful tasks ###

###> composer tasks ###
COMPOSER_CMD=docker run $(DOCKER_RUN_OPTS) $(DOCKER_ORGS)/php:$(PHP_VERSION) composer --ansi

# If composer.json has changed, you need to update composer.lock
composer.lock: composer.json
	@if [ -f $@ ]; \
	then \
		printf $(_WRN) "The $< file has changed. Synchronizing vendor"; \
		rm composer.lock; \
	fi
	@$(MAKE) -s composer-install

vendor: composer.lock
	@$(MAKE) -s composer-install

.PHONY: composer
composer:
	@printf $(_FMT) "$(COMPOSER_CMD)"

.PHONY: composer-clean
composer-clean:
	@if [ -f composer.lock ]; then\
		printf $(_FMT) "rm composer.lock";\
						rm composer.lock;\
	fi
	@if [ -d vendor ]; then\
		printf $(_FMT) "rm -r vendor";\
						rm -r vendor;\
	fi

.PHONY: composer-install
composer-install:
	@printf $(_FMT) "$(COMPOSER_CMD) install --no-progress --prefer-dist --no-suggest"
	@                $(COMPOSER_CMD) install --no-progress --prefer-dist --no-suggest

.PHONY: composer-validate
composer-validate:
	@printf $(_FMT) "$(COMPOSER_CMD) validate"
	@                $(COMPOSER_CMD) validate
###< composer tasks ###
